target = rOne;
text[0] = "DUDE WHAT THE FUCK IS UP!";
text[1] = "THIS ONE SAYS SOMETHING DIFFERENT!";
text[2] = "HOW, YOU MIGHT ASK?";
text[3] = "WELL, OBVIOUSLY BECAUSE VLAD IS A GODDAMN CODING GENIUS! NOW I'M OFF TO LICK MY OWN ASS!!!";